/*
* generated by Xtext
*/

package org.eclipselabs.recommenders.codesearch.rcp.dslQL1.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class QL1GrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class MethodPatternElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MethodPattern");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cModifiersAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cModifiersModifierParserRuleCall_0_0 = (RuleCall)cModifiersAssignment_0.eContents().get(0);
		private final Assignment cReturnTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cReturnTypeReturnTypeParserRuleCall_1_0 = (RuleCall)cReturnTypeAssignment_1.eContents().get(0);
		private final Assignment cMethodNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMethodNameMethodNameParserRuleCall_2_0 = (RuleCall)cMethodNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cParameterElementsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cParameterElementsParameterElementParserRuleCall_3_1_0 = (RuleCall)cParameterElementsAssignment_3_1.eContents().get(0);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cCommaKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cParameterElementsAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final RuleCall cParameterElementsParameterElementParserRuleCall_3_2_1_0 = (RuleCall)cParameterElementsAssignment_3_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3_3 = (Keyword)cGroup_3.eContents().get(3);
		private final Assignment cThrowsClauseAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cThrowsClauseThrowsParserRuleCall_4_0 = (RuleCall)cThrowsClauseAssignment_4.eContents().get(0);
		
		//MethodPattern:
		//	modifiers+=Modifier* returnType=ReturnType methodName=MethodName ("(" parameterElements+=ParameterElement (","
		//	parameterElements+=ParameterElement)* ")")? throwsClause=Throws?;
		public ParserRule getRule() { return rule; }

		//modifiers+=Modifier* returnType=ReturnType methodName=MethodName ("(" parameterElements+=ParameterElement (","
		//parameterElements+=ParameterElement)* ")")? throwsClause=Throws?
		public Group getGroup() { return cGroup; }

		//modifiers+=Modifier*
		public Assignment getModifiersAssignment_0() { return cModifiersAssignment_0; }

		//Modifier
		public RuleCall getModifiersModifierParserRuleCall_0_0() { return cModifiersModifierParserRuleCall_0_0; }

		//returnType=ReturnType
		public Assignment getReturnTypeAssignment_1() { return cReturnTypeAssignment_1; }

		//ReturnType
		public RuleCall getReturnTypeReturnTypeParserRuleCall_1_0() { return cReturnTypeReturnTypeParserRuleCall_1_0; }

		//methodName=MethodName
		public Assignment getMethodNameAssignment_2() { return cMethodNameAssignment_2; }

		//MethodName
		public RuleCall getMethodNameMethodNameParserRuleCall_2_0() { return cMethodNameMethodNameParserRuleCall_2_0; }

		//("(" parameterElements+=ParameterElement ("," parameterElements+=ParameterElement)* ")")?
		public Group getGroup_3() { return cGroup_3; }

		//"("
		public Keyword getLeftParenthesisKeyword_3_0() { return cLeftParenthesisKeyword_3_0; }

		//parameterElements+=ParameterElement
		public Assignment getParameterElementsAssignment_3_1() { return cParameterElementsAssignment_3_1; }

		//ParameterElement
		public RuleCall getParameterElementsParameterElementParserRuleCall_3_1_0() { return cParameterElementsParameterElementParserRuleCall_3_1_0; }

		//("," parameterElements+=ParameterElement)*
		public Group getGroup_3_2() { return cGroup_3_2; }

		//","
		public Keyword getCommaKeyword_3_2_0() { return cCommaKeyword_3_2_0; }

		//parameterElements+=ParameterElement
		public Assignment getParameterElementsAssignment_3_2_1() { return cParameterElementsAssignment_3_2_1; }

		//ParameterElement
		public RuleCall getParameterElementsParameterElementParserRuleCall_3_2_1_0() { return cParameterElementsParameterElementParserRuleCall_3_2_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_3_3() { return cRightParenthesisKeyword_3_3; }

		//throwsClause=Throws?
		public Assignment getThrowsClauseAssignment_4() { return cThrowsClauseAssignment_4; }

		//Throws
		public RuleCall getThrowsClauseThrowsParserRuleCall_4_0() { return cThrowsClauseThrowsParserRuleCall_4_0; }
	}

	public class ModifierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Modifier");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cValueAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final Keyword cValueStaticKeyword_0_0 = (Keyword)cValueAssignment_0.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final Keyword cValuePrivateKeyword_1_0 = (Keyword)cValueAssignment_1.eContents().get(0);
		private final Assignment cValueAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final Keyword cValuePublicKeyword_2_0 = (Keyword)cValueAssignment_2.eContents().get(0);
		private final Assignment cValueAssignment_3 = (Assignment)cAlternatives.eContents().get(3);
		private final Keyword cValueFinalKeyword_3_0 = (Keyword)cValueAssignment_3.eContents().get(0);
		private final Assignment cValueAssignment_4 = (Assignment)cAlternatives.eContents().get(4);
		private final Keyword cValueAbstractKeyword_4_0 = (Keyword)cValueAssignment_4.eContents().get(0);
		private final Assignment cValueAssignment_5 = (Assignment)cAlternatives.eContents().get(5);
		private final Keyword cValueProtectedKeyword_5_0 = (Keyword)cValueAssignment_5.eContents().get(0);
		
		//Modifier:
		//	value="static" | value="private" | value="public" | value="final" | value="abstract" | value="protected";
		public ParserRule getRule() { return rule; }

		//value="static" | value="private" | value="public" | value="final" | value="abstract" | value="protected"
		public Alternatives getAlternatives() { return cAlternatives; }

		//value="static"
		public Assignment getValueAssignment_0() { return cValueAssignment_0; }

		//"static"
		public Keyword getValueStaticKeyword_0_0() { return cValueStaticKeyword_0_0; }

		//value="private"
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//"private"
		public Keyword getValuePrivateKeyword_1_0() { return cValuePrivateKeyword_1_0; }

		//value="public"
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//"public"
		public Keyword getValuePublicKeyword_2_0() { return cValuePublicKeyword_2_0; }

		//value="final"
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }

		//"final"
		public Keyword getValueFinalKeyword_3_0() { return cValueFinalKeyword_3_0; }

		//value="abstract"
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }

		//"abstract"
		public Keyword getValueAbstractKeyword_4_0() { return cValueAbstractKeyword_4_0; }

		//value="protected"
		public Assignment getValueAssignment_5() { return cValueAssignment_5; }

		//"protected"
		public Keyword getValueProtectedKeyword_5_0() { return cValueProtectedKeyword_5_0; }
	}

	public class ReturnTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ReturnType");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueNameWithWCTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//ReturnType:
		//	value=NameWithWC;
		public ParserRule getRule() { return rule; }

		//value=NameWithWC
		public Assignment getValueAssignment() { return cValueAssignment; }

		//NameWithWC
		public RuleCall getValueNameWithWCTerminalRuleCall_0() { return cValueNameWithWCTerminalRuleCall_0; }
	}

	public class ParameterElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ParameterElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cParameterElementAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cValuesAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cValuesParameterTypeParserRuleCall_0_1_0 = (RuleCall)cValuesAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cTypesAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cTypesParameterTypeParserRuleCall_1_1_0 = (RuleCall)cTypesAssignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cTypesAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cTypesParameterTypeParserRuleCall_1_2_1_0 = (RuleCall)cTypesAssignment_1_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		
		//ParameterElement:
		//	{ParameterElement} values+=ParameterType | "{" types+=ParameterType ("," types+=ParameterType)* "}";
		public ParserRule getRule() { return rule; }

		//{ParameterElement} values+=ParameterType | "{" types+=ParameterType ("," types+=ParameterType)* "}"
		public Alternatives getAlternatives() { return cAlternatives; }

		//{ParameterElement} values+=ParameterType
		public Group getGroup_0() { return cGroup_0; }

		//{ParameterElement}
		public Action getParameterElementAction_0_0() { return cParameterElementAction_0_0; }

		//values+=ParameterType
		public Assignment getValuesAssignment_0_1() { return cValuesAssignment_0_1; }

		//ParameterType
		public RuleCall getValuesParameterTypeParserRuleCall_0_1_0() { return cValuesParameterTypeParserRuleCall_0_1_0; }

		//"{" types+=ParameterType ("," types+=ParameterType)* "}"
		public Group getGroup_1() { return cGroup_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1_0() { return cLeftCurlyBracketKeyword_1_0; }

		//types+=ParameterType
		public Assignment getTypesAssignment_1_1() { return cTypesAssignment_1_1; }

		//ParameterType
		public RuleCall getTypesParameterTypeParserRuleCall_1_1_0() { return cTypesParameterTypeParserRuleCall_1_1_0; }

		//("," types+=ParameterType)*
		public Group getGroup_1_2() { return cGroup_1_2; }

		//","
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }

		//types+=ParameterType
		public Assignment getTypesAssignment_1_2_1() { return cTypesAssignment_1_2_1; }

		//ParameterType
		public RuleCall getTypesParameterTypeParserRuleCall_1_2_1_0() { return cTypesParameterTypeParserRuleCall_1_2_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_1_3() { return cRightCurlyBracketKeyword_1_3; }
	}

	public class ParameterTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ParameterType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cValueAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cValueNameWithWCTerminalRuleCall_0_0 = (RuleCall)cValueAssignment_0.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final Keyword cValueFullStopFullStopKeyword_1_0 = (Keyword)cValueAssignment_1.eContents().get(0);
		
		//ParameterType:
		//	value=NameWithWC | value="..";
		public ParserRule getRule() { return rule; }

		//value=NameWithWC | value=".."
		public Alternatives getAlternatives() { return cAlternatives; }

		//value=NameWithWC
		public Assignment getValueAssignment_0() { return cValueAssignment_0; }

		//NameWithWC
		public RuleCall getValueNameWithWCTerminalRuleCall_0_0() { return cValueNameWithWCTerminalRuleCall_0_0; }

		//value=".."
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//".."
		public Keyword getValueFullStopFullStopKeyword_1_0() { return cValueFullStopFullStopKeyword_1_0; }
	}

	public class ThrowsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Throws");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cThrowsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueNameWithWCTerminalRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		
		//Throws:
		//	"throws" value=NameWithWC;
		public ParserRule getRule() { return rule; }

		//"throws" value=NameWithWC
		public Group getGroup() { return cGroup; }

		//"throws"
		public Keyword getThrowsKeyword_0() { return cThrowsKeyword_0; }

		//value=NameWithWC
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//NameWithWC
		public RuleCall getValueNameWithWCTerminalRuleCall_1_0() { return cValueNameWithWCTerminalRuleCall_1_0; }
	}

	public class MethodNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MethodName");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueNameWithWCTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//MethodName:
		//	value=NameWithWC;
		public ParserRule getRule() { return rule; }

		//value=NameWithWC
		public Assignment getValueAssignment() { return cValueAssignment; }

		//NameWithWC
		public RuleCall getValueNameWithWCTerminalRuleCall_0() { return cValueNameWithWCTerminalRuleCall_0; }
	}
	
	
	private MethodPatternElements pMethodPattern;
	private ModifierElements pModifier;
	private ReturnTypeElements pReturnType;
	private ParameterElementElements pParameterElement;
	private ParameterTypeElements pParameterType;
	private ThrowsElements pThrows;
	private MethodNameElements pMethodName;
	private TerminalRule tNameWithWC;
	
	private final GrammarProvider grammarProvider;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public QL1GrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammarProvider = grammarProvider;
		this.gaTerminals = gaTerminals;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//MethodPattern:
	//	modifiers+=Modifier* returnType=ReturnType methodName=MethodName ("(" parameterElements+=ParameterElement (","
	//	parameterElements+=ParameterElement)* ")")? throwsClause=Throws?;
	public MethodPatternElements getMethodPatternAccess() {
		return (pMethodPattern != null) ? pMethodPattern : (pMethodPattern = new MethodPatternElements());
	}
	
	public ParserRule getMethodPatternRule() {
		return getMethodPatternAccess().getRule();
	}

	//Modifier:
	//	value="static" | value="private" | value="public" | value="final" | value="abstract" | value="protected";
	public ModifierElements getModifierAccess() {
		return (pModifier != null) ? pModifier : (pModifier = new ModifierElements());
	}
	
	public ParserRule getModifierRule() {
		return getModifierAccess().getRule();
	}

	//ReturnType:
	//	value=NameWithWC;
	public ReturnTypeElements getReturnTypeAccess() {
		return (pReturnType != null) ? pReturnType : (pReturnType = new ReturnTypeElements());
	}
	
	public ParserRule getReturnTypeRule() {
		return getReturnTypeAccess().getRule();
	}

	//ParameterElement:
	//	{ParameterElement} values+=ParameterType | "{" types+=ParameterType ("," types+=ParameterType)* "}";
	public ParameterElementElements getParameterElementAccess() {
		return (pParameterElement != null) ? pParameterElement : (pParameterElement = new ParameterElementElements());
	}
	
	public ParserRule getParameterElementRule() {
		return getParameterElementAccess().getRule();
	}

	//ParameterType:
	//	value=NameWithWC | value="..";
	public ParameterTypeElements getParameterTypeAccess() {
		return (pParameterType != null) ? pParameterType : (pParameterType = new ParameterTypeElements());
	}
	
	public ParserRule getParameterTypeRule() {
		return getParameterTypeAccess().getRule();
	}

	//Throws:
	//	"throws" value=NameWithWC;
	public ThrowsElements getThrowsAccess() {
		return (pThrows != null) ? pThrows : (pThrows = new ThrowsElements());
	}
	
	public ParserRule getThrowsRule() {
		return getThrowsAccess().getRule();
	}

	//MethodName:
	//	value=NameWithWC;
	public MethodNameElements getMethodNameAccess() {
		return (pMethodName != null) ? pMethodName : (pMethodName = new MethodNameElements());
	}
	
	public ParserRule getMethodNameRule() {
		return getMethodNameAccess().getRule();
	}

	//terminal NameWithWC:
	//	("a".."z" | "A".."Z" | "_" | "*" | "?") ("a".."z" | "A".."Z" | "_" | "0".."9" | "*" | "?" | ".")*;
	public TerminalRule getNameWithWCRule() {
		return (tNameWithWC != null) ? tNameWithWC : (tNameWithWC = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "NameWithWC"));
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
