/*
 * generated by Xtext
 */
package org.eclipselabs.recommenders.codesearchquery.rcp.dslQL1.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class QL1ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.eclipselabs.recommenders.codesearchquery.rcp.dslQL1.ui.internal.QL1Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.eclipselabs.recommenders.codesearchquery.rcp.dslQL1.ui.internal.QL1Activator.getInstance().getInjector("org.eclipselabs.recommenders.codesearchquery.rcp.dslQL1.QL1");
	}
	
}
