/*
 * generated by Xtext
 */
package org.eclipselabs.recommenders.codesearch.internal.rcp.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LuceneFieldsUiModule extends org.eclipselabs.recommenders.codesearch.internal.rcp.dsl.ui.AbstractLuceneFieldsUiModule {
	public LuceneFieldsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
