/*
 * generated by Xtext
 */
package org.eclipselabs.recommenders.codesearch.rcp.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LuceneQueryRuntimeModule extends org.eclipselabs.recommenders.codesearch.rcp.dsl.AbstractLuceneQueryRuntimeModule {

}
