/*
 * generated by Xtext
 */
package org.eclipselabs.recommenders.codesearch.rcp.dslQL2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class QL2UiModule extends org.eclipselabs.recommenders.codesearch.rcp.dslQL2.ui.AbstractQL2UiModule {
	public QL2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
