/*
* generated by Xtext
*/
package org.eclipselabs.recommenders.codesearch.rcp.dslQL2;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class QL2UiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipselabs.recommenders.codesearch.rcp.dslQL2.ui.internal.QL2Activator.getInstance().getInjector("org.eclipselabs.recommenders.codesearch.rcp.dslQL2.QL2");
	}
	
}
