/*
* generated by Xtext
*/
package org.eclipselabs.recommenders.codesearchquery.internal.rcp.dsl.ui.contentassist;

import org.eclipselabs.recommenders.codesearchquery.internal.rcp.dsl.ui.contentassist.AbstractLuceneFieldsProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class LuceneFieldsProposalProvider extends AbstractLuceneFieldsProposalProvider {

}
