/*
 * generated by Xtext
 */
package org.eclipselabs.recommenders.codesearchquery.rcp.dslQL1;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QL1RuntimeModule extends org.eclipselabs.recommenders.codesearchquery.rcp.dslQL1.AbstractQL1RuntimeModule {

}
