/*
 * generated by Xtext
 */
package org.eclipselabs.recommenders.codesearchquery.internal.rcp.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LuceneFieldsRuntimeModule extends org.eclipselabs.recommenders.codesearchquery.internal.rcp.dsl.AbstractLuceneFieldsRuntimeModule {

}
