/*
* generated by Xtext
*/
package org.eclipselabs.recommenders.codesearchquery.rcp.dslQL1;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class QL1UiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipselabs.recommenders.codesearchquery.rcp.dslQL1.ui.internal.QL1Activator.getInstance().getInjector("org.eclipselabs.recommenders.codesearchquery.rcp.dslQL1.QL1");
	}
	
}
