/*
* generated by Xtext
*/
package org.eclipselabs.recommenders.codesearchquery.rcp.dslQL1.ui.contentassist;

import org.eclipselabs.recommenders.codesearchquery.rcp.dslQL1.ui.contentassist.AbstractQL1ProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class QL1ProposalProvider extends AbstractQL1ProposalProvider {

}
