/*
 * generated by Xtext
 */
package org.eclipselabs.recommenders.codesearch.rcp.dslQL2.ui.contentassist;


/**
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on
 * how to customize content assistant
 */
public class QL2ProposalProvider extends AbstractQL2ProposalProvider {

    // @Override
    // public void complete_VarName(EObject model, RuleCall ruleCall,
    // ContentAssistContext context,
    // ICompletionProposalAcceptor acceptor) {
    //
    // VariableExtractor e = new VariableExtractor();
    //
    // // for (VariableUsage var : e.getVars(model)) {
    // // acceptor.accept(createCompletionProposal(var.name, context));
    // // }
    // }
}
