/*
 * generated by Xtext
 */
package org.eclipselabs.recommenders.codesearch.rcp.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LuceneQueryUiModule extends org.eclipselabs.recommenders.codesearch.rcp.dsl.ui.AbstractLuceneQueryUiModule {
	public LuceneQueryUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
