/**
 * Copyright (c) 2012 Tobias Boehm.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *    Tobias Boehm - initial API and implementation.
 */

/*
 * generated by Xtext
 */
package org.eclipselabs.recommenders.codesearch.rcp.dslQL1.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class QL1UiModule extends org.eclipselabs.recommenders.codesearch.rcp.dslQL1.ui.AbstractQL1UiModule {
	public QL1UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
