/*
* generated by Xtext
*/
package org.eclipselabs.recommenders.codesearch.rcp.dslQL1.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.eclipselabs.recommenders.codesearch.rcp.dslQL1.services.QL1GrammarAccess;

public class QL1Parser extends AbstractContentAssistParser {
	
	@Inject
	private QL1GrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.eclipselabs.recommenders.codesearch.rcp.dslQL1.ui.contentassist.antlr.internal.InternalQL1Parser createParser() {
		org.eclipselabs.recommenders.codesearch.rcp.dslQL1.ui.contentassist.antlr.internal.InternalQL1Parser result = new org.eclipselabs.recommenders.codesearch.rcp.dslQL1.ui.contentassist.antlr.internal.InternalQL1Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModifierAccess().getAlternatives(), "rule__Modifier__Alternatives");
					put(grammarAccess.getParameterElementAccess().getAlternatives(), "rule__ParameterElement__Alternatives");
					put(grammarAccess.getParameterTypeAccess().getAlternatives(), "rule__ParameterType__Alternatives");
					put(grammarAccess.getMethodPatternAccess().getGroup(), "rule__MethodPattern__Group__0");
					put(grammarAccess.getMethodPatternAccess().getGroup_3(), "rule__MethodPattern__Group_3__0");
					put(grammarAccess.getMethodPatternAccess().getGroup_3_2(), "rule__MethodPattern__Group_3_2__0");
					put(grammarAccess.getParameterElementAccess().getGroup_0(), "rule__ParameterElement__Group_0__0");
					put(grammarAccess.getParameterElementAccess().getGroup_1(), "rule__ParameterElement__Group_1__0");
					put(grammarAccess.getParameterElementAccess().getGroup_1_2(), "rule__ParameterElement__Group_1_2__0");
					put(grammarAccess.getThrowsAccess().getGroup(), "rule__Throws__Group__0");
					put(grammarAccess.getMethodPatternAccess().getModifiersAssignment_0(), "rule__MethodPattern__ModifiersAssignment_0");
					put(grammarAccess.getMethodPatternAccess().getReturnTypeAssignment_1(), "rule__MethodPattern__ReturnTypeAssignment_1");
					put(grammarAccess.getMethodPatternAccess().getMethodNameAssignment_2(), "rule__MethodPattern__MethodNameAssignment_2");
					put(grammarAccess.getMethodPatternAccess().getParameterElementsAssignment_3_1(), "rule__MethodPattern__ParameterElementsAssignment_3_1");
					put(grammarAccess.getMethodPatternAccess().getParameterElementsAssignment_3_2_1(), "rule__MethodPattern__ParameterElementsAssignment_3_2_1");
					put(grammarAccess.getMethodPatternAccess().getThrowsClauseAssignment_4(), "rule__MethodPattern__ThrowsClauseAssignment_4");
					put(grammarAccess.getModifierAccess().getValueAssignment_0(), "rule__Modifier__ValueAssignment_0");
					put(grammarAccess.getModifierAccess().getValueAssignment_1(), "rule__Modifier__ValueAssignment_1");
					put(grammarAccess.getModifierAccess().getValueAssignment_2(), "rule__Modifier__ValueAssignment_2");
					put(grammarAccess.getModifierAccess().getValueAssignment_3(), "rule__Modifier__ValueAssignment_3");
					put(grammarAccess.getModifierAccess().getValueAssignment_4(), "rule__Modifier__ValueAssignment_4");
					put(grammarAccess.getModifierAccess().getValueAssignment_5(), "rule__Modifier__ValueAssignment_5");
					put(grammarAccess.getReturnTypeAccess().getValueAssignment(), "rule__ReturnType__ValueAssignment");
					put(grammarAccess.getParameterElementAccess().getValuesAssignment_0_1(), "rule__ParameterElement__ValuesAssignment_0_1");
					put(grammarAccess.getParameterElementAccess().getTypesAssignment_1_1(), "rule__ParameterElement__TypesAssignment_1_1");
					put(grammarAccess.getParameterElementAccess().getTypesAssignment_1_2_1(), "rule__ParameterElement__TypesAssignment_1_2_1");
					put(grammarAccess.getParameterTypeAccess().getValueAssignment_0(), "rule__ParameterType__ValueAssignment_0");
					put(grammarAccess.getParameterTypeAccess().getValueAssignment_1(), "rule__ParameterType__ValueAssignment_1");
					put(grammarAccess.getThrowsAccess().getValueAssignment_1(), "rule__Throws__ValueAssignment_1");
					put(grammarAccess.getMethodNameAccess().getValueAssignment(), "rule__MethodName__ValueAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.eclipselabs.recommenders.codesearch.rcp.dslQL1.ui.contentassist.antlr.internal.InternalQL1Parser typedParser = (org.eclipselabs.recommenders.codesearch.rcp.dslQL1.ui.contentassist.antlr.internal.InternalQL1Parser) parser;
			typedParser.entryRuleMethodPattern();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public QL1GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(QL1GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
